import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [index("routes/_index.tsx"),

  route("how-to-invest-in-whisky", "./routes/how-to-invest-in-whisky.tsx"),
  route("how-to-use-the-pie-menu-in-blender", "./routes/how-to-use-the-pie-menu-in-blender.tsx"),
  route("three-essential-webstorm-shortcuts", "./routes/three-essential-webstorm-shortcuts.tsx"),
  route("weirdinternetfacts", "./routes/weirdinternetfacts.tsx"),
  route("nab-2023-audio-video-gear", "./routes/nab-2023-audio-video-gear.tsx"),
  route("threekeys-to-getting-a-frontend-or-fullstackjob", "./routes/threekeys-to-getting-a-frontend-or-fullstackjob.tsx"),
  route("vuejs-independant-javascript-framework", "./routes/vuejs-independant-javascript-framework.tsx"),
  route("astro-the-most-innovative-javascript-framework", "./routes/astro-the-most-innovative-javascript-framework.tsx"),
  route("the-art-of-the-clean-install", "./routes/the-art-of-the-clean-install.tsx"),
  route("what-is-rag", "./routes/what-is-rag.tsx"),
  route("what-are-the-best-free-text-to-speech-tools", "./routes/what-are-the-best-free-text-to-speech-tools.tsx"),
  route("10-essential-pytorch-elements-in-a-rnn", "./routes/10-essential-pytorch-elements-in-a-rnn.tsx"),
  route("10_Essential_PyTorch_Elements_in_LSTMs", "./routes/10_Essential_PyTorch_Elements_in_LSTMs.tsx"),
  route("10_Ways_to_Optimize_SQLite_Before_Migrating_to_PostgreSQL", "./routes/10_Ways_to_Optimize_SQLite_Before_Migrating_to_PostgreSQL.tsx"),
  route("introduction-to-neural-networks", "./routes/introduction-to-neural-networks.tsx"),
  route("dspy101", "./routes/dspy101.tsx"),
  route("create-your-own-huggingface-space-easy", "./routes/create-your-own-huggingface-space-easy.tsx"),
  route("the-ultimate-guide-to-flyers-in-blender-with-the-node-editor", "./routes/the-ultimate-guide-to-flyers-in-blender-with-the-node-editor.tsx"),
  route("about", "./routes/about.tsx"),
  route("using-airpods-and-audacity-hack", "./routes/using-airpods-and-audacity-hack.tsx"),
  route("threejs-and-web3", "./routes/threejs-and-web3.tsx"),
  route("databricks-dspy-jetblue-ai-chatbot", "./routes/databricks-dspy-jetblue-ai-chatbot.tsx"),
  route("5-ways-ai-can-help-farmland-restoration", "./routes/5-ways-ai-can-help-farmland-restoration.tsx"),
  route("5-ways-to-enhance-rag-efficiency-with-dspy", "./routes/5-ways-to-enhance-rag-efficiency-with-dspy.tsx"),
  route("articles/:slug", "./routes/articles.$slug.tsx"),
  route("correlations-archive", "./routes/correlations-archive.tsx"),
  route("archive", "./routes/archive._index.tsx"),
  route("archive/:type", "./routes/archive.$type.tsx"),
  route("snapstate-persistent-state-for-ai-agent-workflows", "./routes/snapstate-persistent-state-for-ai-agent-workflows.tsx"),
  route("continuous-pentesting-ci-guide", "./routes/continuous-pentesting-ci-guide.tsx"),
] satisfies RouteConfig;
