import { Link, data } from "react-router";
import type { LoaderFunctionArgs, MetaFunction } from "react-router";
import { getAllArticleCards, getArticleTypes } from "~/lib/articles-static.server";
import type { ArticleCard } from "~/types/article";

export async function loader(_args: LoaderFunctionArgs) {
  const cards = getAllArticleCards();
  const types = getArticleTypes();
  return data(
    { cards, types },
    {
      headers: {
        "Cache-Control": "public, max-age=600, stale-while-revalidate=1800",
      },
    },
  );
}

export const meta: MetaFunction = () => [
  { title: "Article Archive — Tasty Tech Bytes" },
  {
    name: "description",
    content:
      "Daily AI-generated market articles: stories, blog posts, correlations, and more.",
  },
];

const TYPE_GRADIENTS: Record<string, string> = {
  story: "from-purple-500 via-pink-500 to-rose-500",
  blog: "from-blue-500 via-cyan-500 to-teal-500",
  correlation: "from-emerald-500 via-green-500 to-lime-500",
  review: "from-orange-500 via-amber-500 to-yellow-500",
  morning: "from-fuchsia-500 via-purple-500 to-indigo-500",
  macro: "from-rose-500 via-pink-500 to-fuchsia-500",
  "ai-summary": "from-sky-500 via-blue-500 to-indigo-500",
};

function gradientFor(id: string): string {
  return TYPE_GRADIENTS[id] ?? "from-slate-500 to-slate-700";
}

export default function ArchiveIndex({
  loaderData,
}: {
  loaderData: { cards: ArticleCard[]; types: { id: string; label: string; category: string }[] };
}) {
  const { types, cards } = loaderData;
  const cardByType = new Map<string, ArticleCard>();
  for (const c of cards) {
    const tag = (c.category ?? "").toLowerCase();
    const t = types.find((x) => x.category.toLowerCase() === tag);
    if (t && !cardByType.has(t.id)) cardByType.set(t.id, c);
  }

  return (
    <main className="min-h-screen bg-black">
      <header className="relative overflow-hidden border-b border-gray-200">
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-600" />
        <div className="absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_20%_20%,rgba(255,255,255,0.4),transparent_50%),radial-gradient(circle_at_80%_60%,rgba(255,255,255,0.3),transparent_50%)]" />
        <div className="relative container mx-auto px-4 py-12 sm:py-16 text-white">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-sm font-semibold opacity-80 hover:opacity-100 mb-6 transition-opacity"
          >
            ← Back to home
          </Link>
          <div className="flex items-center gap-3 mb-3">
            <span className="text-3xl sm:text-4xl">📚</span>
            <span className="rounded-full bg-white/15 backdrop-blur px-3 py-1 text-xs font-bold uppercase tracking-widest">
              Daily AI Articles
            </span>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black leading-tight tracking-tight drop-shadow-sm">
            The Archive
          </h1>
          <p className="mt-4 text-base sm:text-lg max-w-2xl opacity-95">
            Seven flavors of daily market intelligence — each generated by an
            independent AI pipeline, written fresh every morning.
          </p>
        </div>
      </header>

      <section className="container mx-auto px-4 py-10 sm:py-14">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {types.map((t) => {
            const card = cardByType.get(t.id);
            const gradient = gradientFor(t.id);
            return (
              <Link
                key={t.id}
                to={`/archive/${t.id}`}
                className="group relative overflow-hidden rounded-2xl shadow-md hover:shadow-2xl transition-all duration-300 hover:-translate-y-1"
              >
                <div className={`absolute inset-0 bg-gradient-to-br ${gradient}`} />
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.25),transparent_60%)]" />
                <div className="relative p-6 text-white min-h-[200px] flex flex-col justify-between">
                  <div>
                    <span className="rounded-full bg-white/20 backdrop-blur px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-widest">
                      {t.id.replace("-", " ")}
                    </span>
                    <h2 className="mt-3 text-2xl font-extrabold">{t.label}</h2>
                    {card && (
                      <p className="mt-2 text-sm opacity-90 line-clamp-2">
                        {card.title}
                      </p>
                    )}
                    {!card && (
                      <p className="mt-2 text-sm opacity-75 italic">
                        No article available today
                      </p>
                    )}
                  </div>
                  <div className="mt-4 inline-flex items-center gap-2 text-sm font-bold">
                    Browse
                    <span className="transition-transform group-hover:translate-x-1">
                      →
                    </span>
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      </section>
    </main>
  );
}
